using PDF_TOC.Proccessing;
using PDF_TOC.Proccessing.Proccessors;
using PDF_TOC.Proccessing.Proccessors.ToC;

var processor = new PdfProccessor();

processor.Proccessors.Add(new DocumentInclude("g.pdf"));
processor.Proccessors.Add(new MetadataProccessor("Chris", "GK - Test"));

var toc = new List<TocItem>()
{
    new("Demografischer Wandel", 1),
    new("Familie", 8),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
};

processor.Proccessors.Add(new ToCProccessor(toc));

processor.Proccessors.Add(new PageNumberRenderer(PdfPagePosition.BottomRight, "X von Y"));

processor.Invoke();