using PDF_TOC.Proccessing;

var processor = new PdfProccessor();

processor.Proccessors.Add(new DocumentInclude("g.pdf"));
processor.Proccessors.Add(new MetadataProccessor("Chris", "GK - Test"));

var toc = new TocItems
{
    new("Demografischer Wandel", 1),
    new("Familie", 8),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
    new("Konfliktlösung im Berufsleben", 16),
};

processor.Proccessors.Add(new ToCProccessor(toc));

processor.Proccessors.Add(new PageNumberRenderer(PdfPagePosition.BottomRight, "X von Y"));

processor.Invoke();